Commit by fathima
Trajectory-Bootcamp/Trajectory-GitHub-Task pull request #5
Opened 2022-12-03 08:09 UTC by mynameisfathima

self Introduction

2022-12-03 17:13 UTC, aravinds-arv requested changes

2022-12-03 17:13 UTC, aravinds-arv commented on tinkerers/Fathima.md
> +https://www.linkedin.com/in/fathima-firoz-0b6b6222b
Heyy Fathima, please use proper markdown syntax to display this URL as a hyperlink.

```
like this 👇
[Linkedin](YOUR_PROFILE_URL)
```

2022-12-04 03:37 UTC, mynameisfathima commented
changes made

2022-12-04 06:26 UTC, merged

2022-12-04 06:26 UTC, aravinds-arv commented
Merged 🎉