committed by Jishnu
Trajectory-Bootcamp/Trajectory-GitHub-Task pull request #7
Opened 2022-12-03 14:01 UTC by JishnuGVarier

2022-12-03 17:16 UTC, aravinds-arv requested changes

2022-12-03 17:16 UTC, aravinds-arv commented on tinkerers/JISHNU_G_VARIER.md
> +- [Linkedin] (http://www.linkedin.com/in/jishnu-g-varier-b3513a227)
Heyy Jishnu, there shouldn't be a space between the square brackets and the rounded brackets. Please remove it to fix the hyperlink

2022-12-04 05:15 UTC, JishnuGVarier commented
done with changes

2022-12-04 06:27 UTC, merged

2022-12-04 06:27 UTC, aravinds-arv commented
Merged 🎉

2022-12-04 07:44 UTC, JishnuGVarier commented
Ok thank you